Character.create(name: 'Finn', image_url: 'finn.jpg', show: 'Adventure Time')
Character.create(name: 'Batman', image_url: 'batman.jpg', show: 'Batman: The Brave and the Bold')
Character.create(name: 'Ben Tennyson', image_url: 'ben10.jpg', show: 'Ben 10 Universe')
Character.create(name: 'The Hacker', image_url: 'hacker.png', show: 'Cyberchase')
Character.create(name: 'Professor Fizzy', image_url: 'fizzy.png', show: 'Fizzy''s Lunch Lab')
Character.create(name: 'Bloo', image_url: 'bloo.jpg', show: 'Foster''s Home for Imaginary Friends')
Character.create(name: 'Mordecai', image_url: 'mordecai.jpg', show: 'Regular Show')
Character.create(name: 'Gumball', image_url: 'gumball.jpg', show: 'The Amazing World of Gumball')
Character.create(name: 'Hero', image_url: 'hero.jpg', show: 'Hero 108')
Character.create(name: 'Pokemon', image_url: 'pokemon.jpg', show: 'Pokemon the Series: XY')
Character.create(name: 'Rigby', image_url: 'rigby.jpg', show: 'Regular Show')
Character.create(name: 'Robin', image_url: 'robin.jpg', show: 'Teen Titans Go!')
Character.create(name: 'Steven', image_url: 'steven.jpg', show: 'Steven''s Universe')
Character.create(name: 'Super Why', image_url: 'super-why.png', show: 'Super Why!')
Character.create(name: 'Word Girl', image_url: 'wordgirl.png', show: 'Word Girl')
Character.create(name: 'Clarence Wendell', image_url: 'clarence.jpg', show: 'Clarence')
Character.create(name: 'Toothless', image_url: 'toothless.jpg', show: 'Dragons: Defenders of Berk')
Character.create(name: 'Johnny Test', image_url: 'jtest.jpg', show: 'Johnny Test')
Character.create(name: 'Kai', image_url: 'kai.jpg', show: 'Ninjago')
Character.create(name: 'Tom', image_url: 'tom.jpg', show: 'Tom and Jerry Show')
Character.create(name: 'Laval', image_url: 'chima.jpg', show: 'Legends of Chima')
Character.create(name: 'Buttercup', image_url: 'powerpuff.jpg', show: 'The Powerpuff Girls')
Character.create(name: 'Dexter', image_url: 'dexter.jpg', show: 'Dexter''s Laboratory')
Character.create(name: 'Chowder', image_url: 'chowder.jpg', show: 'Chowder')
Character.create(name: 'Chris McLean', image_url: 'totaldrama.jpg', show: 'Total Drama: Pahkitew Island')
