###
(->
  $ ->
    $('.selectable').click (e) ->
      $(this).siblings().removeClass 'active dark'
      $(this).addClass 'active dark'
      return
    return
  return
).call this
###
# ---
# generated by js2coffee 2.2.0